name: Node.js CI

on:
  push:
    branches: [ "feature/test-ci" ]
  pull_request:
    branches: [ "feature/test-ci" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: echo "✅ CI Pipeline Running Successfully"

